[package]
name = "tabby-cat"
version = "1.4.0"
edition = "2021"

[dependencies]
error-stack = "0.3.1"
rand = "0.8.5"
webbrowser = "0.8.8"

[dependencies.windows]
version = "0.48.0"
features = ["Win32_Foundation", "Win32_Security", "Win32_System_Threading"]

[profile.release]
lto = true